language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt # install package + test dependencies
script: pytest tests/endtoend/ # run tests
after_success:
  - codecov # submit coverage